#!/bin/sh


# Start all init scripts in /etc/init.d,
# executing them in numerical order.
# After that, do the same for /etc/local/init.d.
#
for i in /etc/init.d/S??* /etc/local/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

